#ifndef _SEC_POLICY_CONFIG2_H_
#define _SEC_POLICY_CONFIG2_H_

/* sboot: disable, lock_state: unlock */

/* download policy */
/* 0: permit download, 1: forbid download */
#define DL_DEFAULT_POLICY_2 		0
#define DL_PL_POLICY_2 				1
#define DL_LK_POLICY_2 				0
#define DL_LOGO_POLICY_2 			0
#define DL_BOOT_POLICY_2 			0
#define DL_RECOVERY_POLICY_2 		0
#define DL_SYSTEM_POLICY_2 			0
#define DL_VENDOR_POLICY_2          0
#define DL_ODM_POLICY_2             0
#define DL_VBMETA_POLICY_2          0
#define DL_TEE1_POLICY_2 			0
#define DL_TEE2_POLICY_2 			0
#define DL_CACHE_POLICY_2 			0
#define DL_SECRO_POLICY_2 			1
#define DL_OEMKEYSTORE_POLICY_2 	0
#define DL_KEYSTORE_POLICY_2 		0
#define DL_USERDATA_POLICY_2 		0
#define DL_MD1IMG_POLICY_2 			0
#define DL_MD1DSP_POLICY_2 			0
#define DL_MD1ARM7_POLICY_2 		0
#define DL_MD3IMG_POLICY_2			0
#define DL_SGPT_POLICY_2 			1
#define DL_PGPT_POLICY_2 			1
#define DL_CAM_VPU1_POLICY_2        0
#define DL_CAM_VPU2_POLICY_2        0
#define DL_CAM_VPU3_POLICY_2        0
#define DL_EFUSE_POLICY_2           0
#define DL_SPMFW_POLICY_2           0
#define DL_MCUPMFW_POLICY_2         0
#define DL_NVRAM_POLICY_2           0
#define DL_PROTECT1_POLICY_2        0
#define DL_PROTECT2_POLICY_2        0
#define DL_PROINFO_POLICY_2         0
#define DL_NVCFG_POLICY_2           0
#define DL_PERSIST_POLICY_2         0
#define DL_ODMDTBO_POLICY_2         0
#define DL_DTBO_POLICY_2            0
#define DL_PERSISTENT_POLICY_2      0
#define DL_VBMETA_SYSTEM_POLICY_2   0
#define DL_VBMETA_VENDOR_POLICY_2   0
#define DL_SUPER_POLICY_2           0

/* verify policy */
/*0: skip verify, 1: need verify */
#define VERIFY_DEFAULT_POLICY_2 	0
#define VERIFY_PL_POLICY_2 			0
#define VERIFY_LK_POLICY_2 			0
#define VERIFY_LOGO_POLICY_2 		0
#define VERIFY_BOOT_POLICY_2 		0
#define VERIFY_RECOVERY_POLICY_2 	0
#define VERIFY_SYSTEM_POLICY_2 	    0
#define VERIFY_VENDOR_POLICY_2      0
#define VERIFY_ODM_POLICY_2         0
#define VERIFY_VBMETA_POLICY_2      0
#define VERIFY_TEE1_POLICY_2 		0
#define VERIFY_TEE2_POLICY_2 		0
#define VERIFY_CACHE_POLICY_2 		0
#define VERIFY_SECRO_POLICY_2 		0
#define VERIFY_OEMKEYSTORE_POLICY_2 0
#define VERIFY_KEYSTORE_POLICY_2 	0
#define VERIFY_USERDATA_POLICY_2 	0
#define VERIFY_MD1IMG_POLICY_2 		0
#define VERIFY_MD1DSP_POLICY_2 		0
#define VERIFY_MD1ARM7_POLICY_2 	0
#define VERIFY_MD3IMG_POLICY_2 		0
#define VERIFY_SGPT_POLICY_2 		0
#define VERIFY_PGPT_POLICY_2 		0
#define VERIFY_CAM_VPU1_POLICY_2    0
#define VERIFY_CAM_VPU2_POLICY_2    0
#define VERIFY_CAM_VPU3_POLICY_2    0
#define VERIFY_EFUSE_POLICY_2       0
#define VERIFY_SPMFW_POLICY_2       0
#define VERIFY_MCUPMFW_POLICY_2     0
#define VERIFY_NVRAM_POLICY_2       0
#define VERIFY_PROTECT1_POLICY_2    0
#define VERIFY_PROTECT2_POLICY_2    0
#define VERIFY_PROINFO_POLICY_2     0
#define VERIFY_NVCFG_POLICY_2       0
#define VERIFY_PERSIST_POLICY_2     0
#define VERIFY_ODMDTBO_POLICY_2     0
#define VERIFY_DTBO_POLICY_2        0
#define VERIFY_PERSISTENT_POLICY_2  0
#define VERIFY_VBMETA_SYSTEM_POLICY_2  0
#define VERIFY_VBMETA_VENDOR_POLICY_2  0
#define VERIFY_SUPER_POLICY_2       0

/* bind to hash policy */
/* 0: skip bind, 1: bind to hash */
#define BIND_DEFAULT_POLICY_2  		0
#define BIND_PL_POLICY_2   			0
#define BIND_LK_POLICY_2   			0 
#define BIND_LOGO_POLICY_2   		0
#define BIND_BOOT_POLICY_2 			0
#define BIND_RECOVERY_POLICY_2 		0
#define BIND_SYSTEM_POLICY_2 		0
#define BIND_VENDOR_POLICY_2        0
#define BIND_ODM_POLICY_2           0
#define BIND_VBMETA_POLICY_2        0
#define BIND_TEE1_POLICY_2 			0
#define BIND_TEE2_POLICY_2 			0
#define BIND_CACHE_POLICY_2 		0
#define BIND_SECRO_POLICY_2 		0
#define BIND_OEMKEYSTORE_POLICY_2 	0
#define BIND_KEYSTORE_POLICY_2 		0
#define BIND_USERDATA_POLICY_2 		0
#define BIND_MD1IMG_POLICY_2 		0
#define BIND_MD1DSP_POLICY_2 		0
#define BIND_MD1ARM7_POLICY_2 		0
#define BIND_MD3IMG_POLICY_2 		0
#define BIND_SGPT_POLICY_2 		    0
#define BIND_PGPT_POLICY_2 		    0
#define BIND_CAM_VPU1_POLICY_2      0
#define BIND_CAM_VPU2_POLICY_2      0
#define BIND_CAM_VPU3_POLICY_2      0
#define BIND_EFUSE_POLICY_2         0
#define BIND_SPMFW_POLICY_2         0
#define BIND_MCUPMFW_POLICY_2       0
#define BIND_NVRAM_POLICY_2         0
#define BIND_PROTECT1_POLICY_2      0
#define BIND_PROTECT2_POLICY_2      0
#define BIND_PROINFO_POLICY_2       0
#define BIND_NVCFG_POLICY_2         0
#define BIND_PERSIST_POLICY_2       0
#define BIND_ODMDTBO_POLICY_2       0
#define BIND_DTBO_POLICY_2          0
#define BIND_PERSISTENT_POLICY_2    0
#define BIND_VBMETA_SYSTEM_POLICY_2 0
#define BIND_VBMETA_VENDOR_POLICY_2 0
#define BIND_SUPER_POLICY_2         0

/* create ap image policy */
#define DEFAULT_SEC_POLICY_2 	CREATE_POLICY_ENTRY(BIND_DEFAULT_POLICY_2, VERIFY_DEFAULT_POLICY_2, DL_DEFAULT_POLICY_2)
#define PL_SEC_POLICY_2     	CREATE_POLICY_ENTRY(BIND_PL_POLICY_2, VERIFY_PL_POLICY_2, DL_PL_POLICY_2)
#define LK_SEC_POLICY_2    		CREATE_POLICY_ENTRY(BIND_LK_POLICY_2, VERIFY_LK_POLICY_2, DL_LK_POLICY_2)
#define LOGO_SEC_POLICY_2    	CREATE_POLICY_ENTRY(BIND_LOGO_POLICY_2, VERIFY_LOGO_POLICY_2, DL_LOGO_POLICY_2)
#define BOOT_SEC_POLICY_2   	CREATE_POLICY_ENTRY(BIND_BOOT_POLICY_2, VERIFY_BOOT_POLICY_2, DL_BOOT_POLICY_2)
#define RECOVERY_SEC_POLICY_2   CREATE_POLICY_ENTRY(BIND_RECOVERY_POLICY_2, VERIFY_RECOVERY_POLICY_2, DL_RECOVERY_POLICY_2)
#define SYSTEM_SEC_POLICY_2  	CREATE_POLICY_ENTRY(BIND_SYSTEM_POLICY_2, VERIFY_SYSTEM_POLICY_2, DL_SYSTEM_POLICY_2)
#define VENDOR_SEC_POLICY_2     CREATE_POLICY_ENTRY(BIND_VENDOR_POLICY_2, VERIFY_VENDOR_POLICY_2, DL_VENDOR_POLICY_2)
#define ODM_SEC_POLICY_2        CREATE_POLICY_ENTRY(BIND_ODM_POLICY_2, VERIFY_ODM_POLICY_2, DL_ODM_POLICY_2)
#define VBMETA_SEC_POLICY_2     CREATE_POLICY_ENTRY(BIND_VBMETA_POLICY_2, VERIFY_VBMETA_POLICY_2, DL_VBMETA_POLICY_2)
#define TEE1_SEC_POLICY_2  		CREATE_POLICY_ENTRY(BIND_TEE1_POLICY_2, VERIFY_TEE1_POLICY_2, DL_TEE1_POLICY_2)
#define TEE2_SEC_POLICY_2  		CREATE_POLICY_ENTRY(BIND_TEE2_POLICY_2, VERIFY_TEE2_POLICY_2, DL_TEE2_POLICY_2)
#define CACHE_SEC_POLICY_2  	CREATE_POLICY_ENTRY(BIND_CACHE_POLICY_2, VERIFY_CACHE_POLICY_2, DL_CACHE_POLICY_2)
#define SECRO_SEC_POLICY_2  	CREATE_POLICY_ENTRY(BIND_SECRO_POLICY_2, VERIFY_SECRO_POLICY_2, DL_SECRO_POLICY_2)
#define OEMKEYSTORE_SEC_POLICY_2 	CREATE_POLICY_ENTRY(BIND_OEMKEYSTORE_POLICY_2, VERIFY_OEMKEYSTORE_POLICY_2, DL_OEMKEYSTORE_POLICY_2)
#define KEYSTORE_SEC_POLICY_2  	CREATE_POLICY_ENTRY(BIND_KEYSTORE_POLICY_2, VERIFY_KEYSTORE_POLICY_2, DL_KEYSTORE_POLICY_2)
#define USERDATA_SEC_POLICY_2  	CREATE_POLICY_ENTRY(BIND_USERDATA_POLICY_2, VERIFY_USERDATA_POLICY_2, DL_USERDATA_POLICY_2)
#define EFUSE_SEC_POLICY_2  	CREATE_POLICY_ENTRY(BIND_EFUSE_POLICY_2, VERIFY_EFUSE_POLICY_2, DL_EFUSE_POLICY_2)
#define SPMFW_SEC_POLICY_2  	CREATE_POLICY_ENTRY(BIND_SPMFW_POLICY_2, VERIFY_SPMFW_POLICY_2, DL_SPMFW_POLICY_2)
#define MCUPMFW_SEC_POLICY_2  	CREATE_POLICY_ENTRY(BIND_MCUPMFW_POLICY_2, VERIFY_MCUPMFW_POLICY_2, DL_MCUPMFW_POLICY_2)

#define SGPT_SEC_POLICY_2       CREATE_POLICY_ENTRY(BIND_SGPT_POLICY_2, VERIFY_SGPT_POLICY_2, DL_SGPT_POLICY_2)
#define PGPT_SEC_POLICY_2       CREATE_POLICY_ENTRY(BIND_PGPT_POLICY_2, VERIFY_PGPT_POLICY_2, DL_PGPT_POLICY_2)
#define NVRAM_SEC_POLICY_2       CREATE_POLICY_ENTRY(BIND_NVRAM_POLICY_2,       VERIFY_NVRAM_POLICY_2,       DL_NVRAM_POLICY_2)
#define PROTECT1_SEC_POLICY_2    CREATE_POLICY_ENTRY(BIND_PROTECT1_POLICY_2,    VERIFY_PROTECT1_POLICY_2,    DL_PROTECT1_POLICY_2)
#define PROTECT2_SEC_POLICY_2    CREATE_POLICY_ENTRY(BIND_PROTECT2_POLICY_2,    VERIFY_PROTECT2_POLICY_2,    DL_PROTECT2_POLICY_2)
#define PROINFO_SEC_POLICY_2     CREATE_POLICY_ENTRY(BIND_PROINFO_POLICY_2,     VERIFY_PROINFO_POLICY_2,     DL_PROINFO_POLICY_2)
#define NVCFG_SEC_POLICY_2       CREATE_POLICY_ENTRY(BIND_NVCFG_POLICY_2,       VERIFY_NVCFG_POLICY_2,       DL_NVCFG_POLICY_2)
#define PERSIST_SEC_POLICY_2     CREATE_POLICY_ENTRY(BIND_PERSIST_POLICY_2,     VERIFY_PERSIST_POLICY_2,     DL_PERSIST_POLICY_2)
#define ODMDTBO_SEC_POLICY_2     CREATE_POLICY_ENTRY(BIND_ODMDTBO_POLICY_2,     VERIFY_ODMDTBO_POLICY_2,     DL_ODMDTBO_POLICY_2)
#define DTBO_SEC_POLICY_2        CREATE_POLICY_ENTRY(BIND_DTBO_POLICY_2,        VERIFY_DTBO_POLICY_2,        DL_DTBO_POLICY_2)
#define PERSISTENT_SEC_POLICY_2  CREATE_POLICY_ENTRY(BIND_PERSISTENT_POLICY_2,  VERIFY_PERSISTENT_POLICY_2,  DL_PERSISTENT_POLICY_2)
#define VBMETA_SYSTEM_SEC_POLICY_2     CREATE_POLICY_ENTRY(BIND_VBMETA_SYSTEM_POLICY_2,     VERIFY_VBMETA_SYSTEM_POLICY_2,     DL_VBMETA_SYSTEM_POLICY_2)
#define VBMETA_VENDOR_SEC_POLICY_2     CREATE_POLICY_ENTRY(BIND_VBMETA_VENDOR_POLICY_2,     VERIFY_VBMETA_VENDOR_POLICY_2,     DL_VBMETA_VENDOR_POLICY_2)
#define SUPER_SEC_POLICY_2     CREATE_POLICY_ENTRY(BIND_SUPER_POLICY_2,     VERIFY_SUPER_POLICY_2,     DL_SUPER_POLICY_2)

/* create md image policy */
#define MD1IMG_SEC_POLICY_2		CREATE_POLICY_ENTRY(BIND_MD1IMG_POLICY_2, VERIFY_MD1IMG_POLICY_2, DL_MD1IMG_POLICY_2)
#define MD1DSP_SEC_POLICY_2		CREATE_POLICY_ENTRY(BIND_MD1DSP_POLICY_2, VERIFY_MD1DSP_POLICY_2, DL_MD1DSP_POLICY_2)
#define MD1ARM7_SEC_POLICY_2	CREATE_POLICY_ENTRY(BIND_MD1ARM7_POLICY_2, VERIFY_MD1ARM7_POLICY_2, DL_MD1ARM7_POLICY_2)
#define MD3IMG_SEC_POLICY_2		CREATE_POLICY_ENTRY(BIND_MD3IMG_POLICY_2, VERIFY_MD3IMG_POLICY_2, DL_MD3IMG_POLICY_2)

/* create cam image policy */
#define CAM_VPU1_SEC_POLICY_2   CREATE_POLICY_ENTRY(BIND_CAM_VPU1_POLICY_2, VERIFY_CAM_VPU1_POLICY_2, DL_CAM_VPU1_POLICY_2)
#define CAM_VPU2_SEC_POLICY_2	CREATE_POLICY_ENTRY(BIND_CAM_VPU2_POLICY_2, VERIFY_CAM_VPU2_POLICY_2, DL_CAM_VPU2_POLICY_2)
#define CAM_VPU3_SEC_POLICY_2	CREATE_POLICY_ENTRY(BIND_CAM_VPU3_POLICY_2, VERIFY_CAM_VPU3_POLICY_2, DL_CAM_VPU3_POLICY_2)

/* custom image security policy */
#define  DL_CUST1_POLICY_2       	0
#define  VERIFY_CUST1_POLICY_2   	0
#define  BIND_CUST1_POLICY_2    	0

#define  DL_CUST2_POLICY_2       	0
#define  VERIFY_CUST2_POLICY_2   	0
#define  BIND_CUST2_POLICY_2    	0

/* create custom image policy */
#define  CUST1_SEC_POLICY_2  CREATE_POLICY_ENTRY(BIND_CUST1_POLICY_2, VERIFY_CUST1_POLICY_2, DL_CUST1_POLICY_2)
#define  CUST2_SEC_POLICY_2  CREATE_POLICY_ENTRY(BIND_CUST2_POLICY_2, VERIFY_CUST2_POLICY_2, DL_CUST2_POLICY_2)

#endif
