#ifndef _SEC_POLICY_CONFIG4_H_
#define _SEC_POLICY_CONFIG4_H_

/* sboot: enable, lock_state: unlock */

/* download policy */
/* 0: permit download, 1: forbid download */
#define DL_DEFAULT_POLICY_4 		0
#define DL_PL_POLICY_4 				0
#define DL_LK_POLICY_4 				0
#define DL_LOGO_POLICY_4 			0
#define DL_BOOT_POLICY_4 			0
#define DL_RECOVERY_POLICY_4 		0
#define DL_SYSTEM_POLICY_4 			0
#define DL_VENDOR_POLICY_4          0
#define DL_ODM_POLICY_4             0
#define DL_VBMETA_POLICY_4          0
#define DL_TEE1_POLICY_4 			0
#define DL_TEE2_POLICY_4 			0
#define DL_CACHE_POLICY_4 			0
#define DL_SECRO_POLICY_4 			0
#define DL_OEMKEYSTORE_POLICY_4 	0
#define DL_KEYSTORE_POLICY_4 		0
#define DL_USERDATA_POLICY_4 		0
#define DL_MD1IMG_POLICY_4 			0
#define DL_MD1DSP_POLICY_4 			0
#define DL_MD1ARM7_POLICY_4 		0
#define DL_MD3IMG_POLICY_4 			0
#define DL_SGPT_POLICY_4 			0
#define DL_PGPT_POLICY_4 			0
#define DL_CAM_VPU1_POLICY_4        0
#define DL_CAM_VPU2_POLICY_4        0
#define DL_CAM_VPU3_POLICY_4        0
#define DL_EFUSE_POLICY_4           0
#define DL_SPMFW_POLICY_4           0
#define DL_MCUPMFW_POLICY_4         0
#define DL_NVRAM_POLICY_4           0
#define DL_PROTECT1_POLICY_4        0
#define DL_PROTECT2_POLICY_4        0
#define DL_PROINFO_POLICY_4         0
#define DL_NVCFG_POLICY_4           0
#define DL_PERSIST_POLICY_4         0
#define DL_ODMDTBO_POLICY_4         0
#define DL_DTBO_POLICY_4            0
#define DL_PERSISTENT_POLICY_4      0
#define DL_VBMETA_SYSTEM_POLICY_4   0
#define DL_VBMETA_VENDOR_POLICY_4   0
#define DL_SUPER_POLICY_4           0
#define DL_MCF1_POLICY_4       0
#define DL_MCF2_POLICY_4       0
#define DL_ROOTFS_POLICY_4     0

/* verify policy */
/* 0: skip verify, 1: need verify */
#define VERIFY_DEFAULT_POLICY_4 	0
#define VERIFY_PL_POLICY_4 			0
#define VERIFY_LK_POLICY_4 			0
#define VERIFY_LOGO_POLICY_4 		0
#define VERIFY_BOOT_POLICY_4 		0
#define VERIFY_RECOVERY_POLICY_4 	0
#define VERIFY_SYSTEM_POLICY_4      0
#define VERIFY_VENDOR_POLICY_4      0
#define VERIFY_ODM_POLICY_4         0
#define VERIFY_VBMETA_POLICY_4      0
#define VERIFY_TEE1_POLICY_4 		0
#define VERIFY_TEE2_POLICY_4 		0
#define VERIFY_CACHE_POLICY_4 		0
#define VERIFY_SECRO_POLICY_4 		0
#define VERIFY_OEMKEYSTORE_POLICY_4 0
#define VERIFY_KEYSTORE_POLICY_4 	0
#define VERIFY_USERDATA_POLICY_4 	0
#define VERIFY_MD1IMG_POLICY_4 		0
#define VERIFY_MD1DSP_POLICY_4 		0
#define VERIFY_MD1ARM7_POLICY_4 	0
#define VERIFY_MD3IMG_POLICY_4 		0
#define VERIFY_SGPT_POLICY_4 		0
#define VERIFY_PGPT_POLICY_4 		0
#define VERIFY_CAM_VPU1_POLICY_4    0
#define VERIFY_CAM_VPU2_POLICY_4    0
#define VERIFY_CAM_VPU3_POLICY_4    0
#define VERIFY_EFUSE_POLICY_4       0
#define VERIFY_SPMFW_POLICY_4       0
#define VERIFY_MCUPMFW_POLICY_4     0
#define VERIFY_NVRAM_POLICY_4       0
#define VERIFY_PROTECT1_POLICY_4    0
#define VERIFY_PROTECT2_POLICY_4    0
#define VERIFY_PROINFO_POLICY_4     0
#define VERIFY_NVCFG_POLICY_4       0
#define VERIFY_PERSIST_POLICY_4     0
#define VERIFY_ODMDTBO_POLICY_4     0
#define VERIFY_DTBO_POLICY_4        0
#define VERIFY_PERSISTENT_POLICY_4  0
#define VERIFY_VBMETA_SYSTEM_POLICY_4  0
#define VERIFY_VBMETA_VENDOR_POLICY_4  0
#define VERIFY_SUPER_POLICY_4       0
#define VERIFY_MCF1_POLICY_4   0
#define VERIFY_MCF2_POLICY_4   0
#define VERIFY_ROOTFS_POLICY_4 0

/* bind to hash policy */
/* 0: skip bind, 1: bind to hash */
#define BIND_DEFAULT_POLICY_4  		0
#define BIND_PL_POLICY_4   			0
#define BIND_LK_POLICY_4   			0
#define BIND_LOGO_POLICY_4   		0
#define BIND_BOOT_POLICY_4 			0
#define BIND_RECOVERY_POLICY_4 		0
#define BIND_SYSTEM_POLICY_4 		0
#define BIND_VENDOR_POLICY_4        0
#define BIND_ODM_POLICY_4           0
#define BIND_VBMETA_POLICY_4        0
#define BIND_TEE1_POLICY_4 			0
#define BIND_TEE2_POLICY_4 			0
#define BIND_CACHE_POLICY_4 		0
#define BIND_SECRO_POLICY_4 		0
#define BIND_OEMKEYSTORE_POLICY_4 	0
#define BIND_KEYSTORE_POLICY_4 		0
#define BIND_USERDATA_POLICY_4 		0
#define BIND_MD1IMG_POLICY_4 		0
#define BIND_MD1DSP_POLICY_4 		0
#define BIND_MD1ARM7_POLICY_4 		0
#define BIND_MD3IMG_POLICY_4 		0
#define BIND_SGPT_POLICY_4 		    0
#define BIND_PGPT_POLICY_4 		    0
#define BIND_CAM_VPU1_POLICY_4      0
#define BIND_CAM_VPU2_POLICY_4      0
#define BIND_CAM_VPU3_POLICY_4      0
#define BIND_EFUSE_POLICY_4         0
#define BIND_SPMFW_POLICY_4         0
#define BIND_MCUPMFW_POLICY_4       0
#define BIND_NVRAM_POLICY_4         0
#define BIND_PROTECT1_POLICY_4      0
#define BIND_PROTECT2_POLICY_4      0
#define BIND_PROINFO_POLICY_4       0
#define BIND_NVCFG_POLICY_4         0
#define BIND_PERSIST_POLICY_4       0
#define BIND_ODMDTBO_POLICY_4       0
#define BIND_DTBO_POLICY_4          0
#define BIND_PERSISTENT_POLICY_4    0
#define BIND_VBMETA_SYSTEM_POLICY_4 0
#define BIND_VBMETA_VENDOR_POLICY_4 0
#define BIND_SUPER_POLICY_4         0
#define BIND_MCF1_POLICY_4     0
#define BIND_MCF2_POLICY_4     0
#define BIND_ROOTFS_POLICY_4   0

/* create ap image policy */
#define DEFAULT_SEC_POLICY_4 	CREATE_POLICY_ENTRY(BIND_DEFAULT_POLICY_4, VERIFY_DEFAULT_POLICY_4, DL_DEFAULT_POLICY_4)
#define PL_SEC_POLICY_4     	CREATE_POLICY_ENTRY(BIND_PL_POLICY_4, VERIFY_PL_POLICY_4, DL_PL_POLICY_4)
#define LK_SEC_POLICY_4    		CREATE_POLICY_ENTRY(BIND_LK_POLICY_4, VERIFY_LK_POLICY_4, DL_LK_POLICY_4)
#define LOGO_SEC_POLICY_4    	CREATE_POLICY_ENTRY(BIND_LOGO_POLICY_4, VERIFY_LOGO_POLICY_4, DL_LOGO_POLICY_4)
#define BOOT_SEC_POLICY_4   	CREATE_POLICY_ENTRY(BIND_BOOT_POLICY_4, VERIFY_BOOT_POLICY_4, DL_BOOT_POLICY_4)
#define RECOVERY_SEC_POLICY_4  	CREATE_POLICY_ENTRY(BIND_RECOVERY_POLICY_4, VERIFY_RECOVERY_POLICY_4, DL_RECOVERY_POLICY_4)
#define SYSTEM_SEC_POLICY_4  	CREATE_POLICY_ENTRY(BIND_SYSTEM_POLICY_4, VERIFY_SYSTEM_POLICY_4, DL_SYSTEM_POLICY_4)
#define VENDOR_SEC_POLICY_4     CREATE_POLICY_ENTRY(BIND_VENDOR_POLICY_4,  VERIFY_VENDOR_POLICY_4, DL_VENDOR_POLICY_4)
#define ODM_SEC_POLICY_4        CREATE_POLICY_ENTRY(BIND_ODM_POLICY_4, VERIFY_ODM_POLICY_4, DL_ODM_POLICY_4)
#define VBMETA_SEC_POLICY_4     CREATE_POLICY_ENTRY(BIND_VBMETA_POLICY_4, VERIFY_VBMETA_POLICY_4, DL_VBMETA_POLICY_4)
#define TEE1_SEC_POLICY_4  		CREATE_POLICY_ENTRY(BIND_TEE1_POLICY_4, VERIFY_TEE1_POLICY_4, DL_TEE1_POLICY_4)
#define TEE2_SEC_POLICY_4  		CREATE_POLICY_ENTRY(BIND_TEE2_POLICY_4, VERIFY_TEE2_POLICY_4, DL_TEE2_POLICY_4)
#define CACHE_SEC_POLICY_4  	CREATE_POLICY_ENTRY(BIND_CACHE_POLICY_4, VERIFY_CACHE_POLICY_4, DL_CACHE_POLICY_4)
#define SECRO_SEC_POLICY_4  	CREATE_POLICY_ENTRY(BIND_SECRO_POLICY_4, VERIFY_SECRO_POLICY_4, DL_SECRO_POLICY_4)
#define OEMKEYSTORE_SEC_POLICY_4 	CREATE_POLICY_ENTRY(BIND_OEMKEYSTORE_POLICY_4, VERIFY_OEMKEYSTORE_POLICY_4, DL_OEMKEYSTORE_POLICY_4)
#define KEYSTORE_SEC_POLICY_4  	CREATE_POLICY_ENTRY(BIND_KEYSTORE_POLICY_4, VERIFY_KEYSTORE_POLICY_4, DL_KEYSTORE_POLICY_4)
#define USERDATA_SEC_POLICY_4  	CREATE_POLICY_ENTRY(BIND_USERDATA_POLICY_4, VERIFY_USERDATA_POLICY_4, DL_USERDATA_POLICY_4)
#define EFUSE_SEC_POLICY_4  	CREATE_POLICY_ENTRY(BIND_EFUSE_POLICY_4, VERIFY_EFUSE_POLICY_4, DL_EFUSE_POLICY_4)
#define SPMFW_SEC_POLICY_4  	CREATE_POLICY_ENTRY(BIND_SPMFW_POLICY_4, VERIFY_SPMFW_POLICY_4, DL_SPMFW_POLICY_4)
#define MCUPMFW_SEC_POLICY_4  	CREATE_POLICY_ENTRY(BIND_MCUPMFW_POLICY_4, VERIFY_MCUPMFW_POLICY_4, DL_MCUPMFW_POLICY_4)

#define SGPT_SEC_POLICY_4       CREATE_POLICY_ENTRY(BIND_SGPT_POLICY_4, VERIFY_SGPT_POLICY_4, DL_SGPT_POLICY_4)
#define PGPT_SEC_POLICY_4       CREATE_POLICY_ENTRY(BIND_PGPT_POLICY_4, VERIFY_PGPT_POLICY_4, DL_PGPT_POLICY_4)
#define NVRAM_SEC_POLICY_4       CREATE_POLICY_ENTRY(BIND_NVRAM_POLICY_4,       VERIFY_NVRAM_POLICY_4,       DL_NVRAM_POLICY_4)
#define PROTECT1_SEC_POLICY_4    CREATE_POLICY_ENTRY(BIND_PROTECT1_POLICY_4,    VERIFY_PROTECT1_POLICY_4,    DL_PROTECT1_POLICY_4)
#define PROTECT2_SEC_POLICY_4    CREATE_POLICY_ENTRY(BIND_PROTECT2_POLICY_4,    VERIFY_PROTECT2_POLICY_4,    DL_PROTECT2_POLICY_4)
#define PROINFO_SEC_POLICY_4     CREATE_POLICY_ENTRY(BIND_PROINFO_POLICY_4,     VERIFY_PROINFO_POLICY_4,     DL_PROINFO_POLICY_4)
#define NVCFG_SEC_POLICY_4       CREATE_POLICY_ENTRY(BIND_NVCFG_POLICY_4,       VERIFY_NVCFG_POLICY_4,       DL_NVCFG_POLICY_4)
#define PERSIST_SEC_POLICY_4     CREATE_POLICY_ENTRY(BIND_PERSIST_POLICY_4,     VERIFY_PERSIST_POLICY_4,     DL_PERSIST_POLICY_4)
#define ODMDTBO_SEC_POLICY_4     CREATE_POLICY_ENTRY(BIND_ODMDTBO_POLICY_4,     VERIFY_ODMDTBO_POLICY_4,     DL_ODMDTBO_POLICY_4)
#define DTBO_SEC_POLICY_4        CREATE_POLICY_ENTRY(BIND_DTBO_POLICY_4,        VERIFY_DTBO_POLICY_4,        DL_DTBO_POLICY_4)
#define PERSISTENT_SEC_POLICY_4  CREATE_POLICY_ENTRY(BIND_PERSISTENT_POLICY_4,  VERIFY_PERSISTENT_POLICY_4,  DL_PERSISTENT_POLICY_4)
#define VBMETA_SYSTEM_SEC_POLICY_4     CREATE_POLICY_ENTRY(BIND_VBMETA_SYSTEM_POLICY_4,     VERIFY_VBMETA_SYSTEM_POLICY_4,     DL_VBMETA_SYSTEM_POLICY_4)
#define VBMETA_VENDOR_SEC_POLICY_4     CREATE_POLICY_ENTRY(BIND_VBMETA_VENDOR_POLICY_4,     VERIFY_VBMETA_VENDOR_POLICY_4,     DL_VBMETA_VENDOR_POLICY_4)
#define SUPER_SEC_POLICY_4     CREATE_POLICY_ENTRY(BIND_SUPER_POLICY_4,     VERIFY_SUPER_POLICY_4,     DL_SUPER_POLICY_4)
#define ROOTFS_SEC_POLICY_4     CREATE_POLICY_ENTRY(BIND_ROOTFS_POLICY_4,     VERIFY_ROOTFS_POLICY_4,     DL_ROOTFS_POLICY_4)

/* create md image policy */
#define MD1IMG_SEC_POLICY_4		CREATE_POLICY_ENTRY(BIND_MD1IMG_POLICY_4, VERIFY_MD1IMG_POLICY_4, DL_MD1IMG_POLICY_4)
#define MD1DSP_SEC_POLICY_4		CREATE_POLICY_ENTRY(BIND_MD1DSP_POLICY_4, VERIFY_MD1DSP_POLICY_4, DL_MD1DSP_POLICY_4)
#define MD1ARM7_SEC_POLICY_4	CREATE_POLICY_ENTRY(BIND_MD1ARM7_POLICY_4, VERIFY_MD1ARM7_POLICY_4, DL_MD1ARM7_POLICY_4)
#define MD3IMG_SEC_POLICY_4		CREATE_POLICY_ENTRY(BIND_MD3IMG_POLICY_4, VERIFY_MD3IMG_POLICY_4, DL_MD3IMG_POLICY_4)
#define MCF1_SEC_POLICY_4     CREATE_POLICY_ENTRY(BIND_MCF1_POLICY_4,     VERIFY_MCF1_POLICY_4,     DL_MCF1_POLICY_4)
#define MCF2_SEC_POLICY_4     CREATE_POLICY_ENTRY(BIND_MCF2_POLICY_4,     VERIFY_MCF2_POLICY_4,     DL_MCF2_POLICY_4)

/* create cam image policy */
#define CAM_VPU1_SEC_POLICY_4   CREATE_POLICY_ENTRY(BIND_CAM_VPU1_POLICY_4, VERIFY_CAM_VPU1_POLICY_4, DL_CAM_VPU1_POLICY_4)
#define CAM_VPU2_SEC_POLICY_4	CREATE_POLICY_ENTRY(BIND_CAM_VPU2_POLICY_4, VERIFY_CAM_VPU2_POLICY_4, DL_CAM_VPU2_POLICY_4)
#define CAM_VPU3_SEC_POLICY_4	CREATE_POLICY_ENTRY(BIND_CAM_VPU3_POLICY_4, VERIFY_CAM_VPU3_POLICY_4, DL_CAM_VPU3_POLICY_4)

/* custom image security policy */
#define  DL_CUST1_POLICY_4       	0
#define  VERIFY_CUST1_POLICY_4   	0
#define  BIND_CUST1_POLICY_4    	0

#define  DL_CUST2_POLICY_4       	0
#define  VERIFY_CUST2_POLICY_4   	0
#define  BIND_CUST2_POLICY_4    	0

/* create custom image policy */
#define  CUST1_SEC_POLICY_4  CREATE_POLICY_ENTRY(BIND_CUST1_POLICY_4, VERIFY_CUST1_POLICY_4, DL_CUST1_POLICY_4)
#define  CUST2_SEC_POLICY_4  CREATE_POLICY_ENTRY(BIND_CUST2_POLICY_4, VERIFY_CUST2_POLICY_4, DL_CUST2_POLICY_4)

#endif
