#pragma once


//main
#define CMD_UNKNOWN "CMD:UNKNOWN"

#define CMD_WRITE_PARTITION "CMD:WRITE-PARTITION"
#define CMD_WRITE_PARTITIONS "CMD:WRITE-PARTITIONS"
#define CMD_WRITE_FLASH "CMD:WRITE-FLASH"
#define CMD_READ_PARTITION "CMD:READ-PARTITION"
#define CMD_READ_PARTITION_TABLE "CMD:READ-PARTITION-TABLE"
#define CMD_READ_FLASH "CMD:READ-FLASH"
#define CMD_FLASH_ALL "CMD:FLASH-ALL"
#define CMD_FLASH_UPDATE "CMD:FLASH-UPDATE"
#define CMD_ERASE_PARTITION "CMD:ERASE-PARTITION"
#define CMD_ERASE_FLASH "CMD:ERASE-FLASH"
#define CMD_NOTIFY_INIT_HW "CMD:NOTIFY-INIT-HW"
#define CMD_SET_HOST_INFO "CMD:SET-HOST-INFO"
#define CMD_BOOT_TO "CMD:BOOT-TO"
#define CMD_REBOOT "CMD:REBOOT"
#define CMD_READ_EFUSE "CMD:READ-EFUSE"
#define CMD_WRITE_EFUSE "CMD:WRITE-EFUSE"
#define CMD_RAM_TEST "CMD:RAM-TEST"
#define CMD_WRITE_PRIVATE_CERT "CMD:WRITE-PRIVATE-CERT"
#define CMD_GET_HW_INFO "CMD:GET-HW-INFO"

#define CMD_SET_BOOT_MODE "CMD:SET-BOOT-MODE"
#define CMD_SET_RSC "CMD:SET-RSC"

#define CMD_SET_RUNTIME_PARAM "CMD:SET-RUNTIME-PARAMETER"
#define CMD_GET_DA_INFO "CMD:GET-DA-INFO"
#define CMD_EMMC_CONTROL "CMD:EMMC-CONTROL"
#define CMD_DEBUG_DRAM_REPAIR "CMD:DEBUG:DRAM-REPAIR"
#define CMD_DEBUG_UFS "CMD:DEBUG:UFS"

#define CMD_READ_REGISTER "CMD:READ-REGISTER"
#define CMD_WRITE_REGISTER "CMD:WRITE-REGISTER"

#define CMD_SECURITY_SET_ALLINONE_SIGNATURE "CMD:SECURITY-SET-ALLINONE-SIGNATURE"
#define CMD_SECURITY_SET_FLASH_POLICY "CMD:SECURITY-SET-FLASH-POLICY"
#define CMD_SECURITY_GET_DEV_FW_INFO "CMD:SECURITY-GET-DEV-FW-INFO"
#define CMD_SECURITY_SET_EXTERNAL_SIGNATURE "CMD:SECURITY-SET-EXTERNAL-SIGNATURE"

#define CMD_GET_SYS_PROPERTY "CMD:GET-SYS-PROPERTY"
#define CMD_GET_DOWNLOADED_IMAGE_FEEDBACK "CMD:GET-DOWNLOADED-IMAGE-FEEDBACK"
#define CMD_HOST_SUPPORTED_COMMANDS "CMD:HOST-SUPPORTED-COMMANDS"