//
//  REGISTER.H  Register map include file
//
#ifndef _A60868_REGISTER_H_
#define _A60868_REGISTER_H_

#if FT_DSIM_USED==0
#include "dramc_pi_api.h"
#endif

#define POS_BANK_NUM 16  // SW Virtual base address position

#if !__ETT__ //FIXME: need to porting
#define SPM_BASE_ADDRESS 0x10006000

#define SPM_POWERON_CONFIG_EN (SPM_BASE_ADDRESS + 0x0000)
#define POWERON_CONFIG_EN_BCLK_CG_EN Fld(1, 0, AC_MSKB0)/* [0:0] */
#define POWERON_CONFIG_EN_PROJECT_CODE Fld(16, 16, AC_FULLW32)/* [31:16] */
#define SPM_POWER_ON_VAL0 (SPM_BASE_ADDRESS + 0x0004)
#define SPM_POWER_ON_VAL0_INI_PWRON_REG0_RF Fld(32, 0, AC_FULLDW)/* [31:0] */
#define SPM_POWER_ON_VAL0_SC_DR_SHU_LEVEL_PCM Fld(2, 30, AC_MSKB3)/* [31:30] */
#define SPM_POWER_ON_VAL0_SC_PHYPLL2_MODE_SW_PCM Fld(1, 29, AC_MSKB3)/* [29:29] */
#define SPM_POWER_ON_VAL0_SC_PHYPLL_MODE_SW_PCM Fld(1, 28, AC_MSKB3)/* [28:28] */
#define SPM_POWER_ON_VAL0_SC_PHYPLL2_SHU_EN_PCM Fld(1, 27, AC_MSKB3)/* [27:27] */
#define SPM_POWER_ON_VAL0_SC_PHYPLL_SHU_EN_PCM Fld(1, 26, AC_MSKB3)/* [26:26] */
#define SPM_POWER_ON_VAL0_SC_DPHY_RXDLY_TRACK_EN Fld(1, 25, AC_MSKB3)/* [25:25] */
#define SPM_POWER_ON_VAL0_SC_MPLL_S_OFF Fld(1, 24, AC_MSKB3)/* [24:24] */
#define SPM_POWER_ON_VAL0_SC_DPHY_PRECAL_UP Fld(1, 23, AC_MSKB2)/* [23:23] */
#define SPM_POWER_ON_VAL0_SC_DR_SHU_EN_PCM Fld(1, 22, AC_MSKB2)/* [22:22] */
#define SPM_POWER_ON_VAL0_SC_CKSQ1_OFF Fld(1, 21, AC_MSKB2)/* [21:21] */
#define SPM_POWER_ON_VAL0_SC_CKSQ0_OFF Fld(1, 20, AC_MSKB2)/* [20:20] */
#define SPM_POWER_ON_VAL0_SC_SHU_RESTORE Fld(1, 19, AC_MSKB2)/* [19:19] */
#define SPM_POWER_ON_VAL0_SC_MPLL_OFF Fld(1, 18, AC_MSKB2)/* [18:18] / /BIANCO_TO_BE_PORTING */
#define SPM_POWER_ON_VAL0_SC_DPY_BCLK_ENABLE Fld(1, 17, AC_MSKB2)/* [17:17] */
#define SPM_POWER_ON_VAL0_SC_DDRPHY_FB_CK_EN_PCM Fld(1, 16, AC_MSKB2)/* [16:16] */
#define SPM_POWER_ON_VAL0_SC_PHYPLL_EN_PCM Fld(1, 15, AC_MSKB1)/* [15:15] */
#define SPM_POWER_ON_VAL0_SC_DPY_VREF_EN_PCM Fld(1, 14, AC_MSKB1)/* [14:14] */
#define SPM_POWER_ON_VAL0_SC_DPY_DLL_CK_EN_PCM Fld(1, 13, AC_MSKB1)/* [13:13] */
#define SPM_POWER_ON_VAL0_SC_DPY_DLL_EN_PCM Fld(1, 12, AC_MSKB1)/* [12:12] */
#define SPM_POWER_ON_VAL0_SC_TX_TRACKING_DIS Fld(1, 11, AC_MSKB1)/* [11:11] */
#define SPM_POWER_ON_VAL0_SC_MPLLOUT_OFF Fld(1, 10, AC_MSKB1)/* [10:10] */
/* Empty [9:9] */
#define SPM_POWER_ON_VAL0_SC_DPY_2ND_DLL_EN_PCM Fld(1, 8, AC_MSKB1)/* [8:8] */
#define SPM_POWER_ON_VAL0_SC_DMSUS_OFF_PCM Fld(1, 7, AC_MSKB0)/* [7:7] */
#define SPM_POWER_ON_VAL0_SC_DPY_MODE_SW_PCM Fld(1, 6, AC_MSKB0)/* [6:6] */
#define SPM_POWER_ON_VAL0_SC_MD26M_CK_OFF Fld(1, 5, AC_MSKB0)/* [5:5] */
#define SPM_POWER_ON_VAL0_SC_DR_GATE_RETRY_EN_PCM Fld(1, 4, AC_MSKB0)/* [4:4] */
#define SPM_POWER_ON_VAL0_SC_AXI_CK_OFF Fld(1, 3, AC_MSKB0)/* [3:3] */
#define SPM_POWER_ON_VAL0_SC_MEM_CK_OFF Fld(1, 2, AC_MSKB0)/* [2:2] */
#define SPM_POWER_ON_VAL0_SC_TIMER_RST Fld(1, 1, AC_MSKB0)/* [1:1] */
#define SPM_POWER_ON_VAL0_SC_26M_CK_OFF Fld(1, 0, AC_MSKB0)/* [0:0] */
#define SPM_POWER_ON_VAL1 (SPM_BASE_ADDRESS + 0x0008)
#define SPM_POWER_ON_VAL1_SC_DR_SHORT_QUEUE_PCM Fld(1, 31, AC_MSKB3)/* [31:31] */
#define SPM_POWER_ON_VAL1_EMI_CLK_OFF_REQ_PCM Fld(1, 1, AC_MSKB0)/* [1:1] */
#define SPM_CLK_CON (SPM_BASE_ADDRESS + 0x000C)
#define SPM_CLK_CON_REG_SYSCLK0_EN_CTRL Fld(2, 0, AC_MSKB0)/* [1:0] */
#define SPM_CLK_CON_REG_SYSCLK1_EN_CTRL Fld(2, 2, AC_MSKB0)/* [3:2] */
#define SPM_CLK_CON_REG_SYSSETTLE_SEL Fld(1, 4, AC_MSKB0)/* [4:4] */
#define SPM_CLK_CON_REG_SPM_LOCK_INFRA_DCM Fld(1, 5, AC_MSKB0)/* [5:5] */
#define SPM_CLK_CON_REG_EXT_SRCCLKEN_MASK Fld(3, 6, AC_MSKW10)/* [8:6] */
#define SPM_CLK_CON_REG_CXO32K_REMOVE_EN_MD1 Fld(1, 9, AC_MSKB1)/* [9:9] */
#define SPM_CLK_CON_REG_CXO32K_REMOVE_EN_MD2 Fld(1, 10, AC_MSKB1)/* [10:10] */
#define SPM_CLK_CON_REG_CLKSQ0_SEL_CTRL Fld(1, 11, AC_MSKB1)/* [11:11] */
#define SPM_CLK_CON_REG_CLKSQ1_SEL_CTRL Fld(1, 12, AC_MSKB1)/* [12:12] */
#define SPM_CLK_CON_REG_SRCCLKEN0_EN Fld(1, 13, AC_MSKB1)/* [13:13] */
#define SPM_CLK_CON_REG_SRCCLKEN1_EN Fld(1, 14, AC_MSKB1)/* [14:14] */
#define SPM_CLK_CON_REG_SCP_DCM_EN Fld(1, 15, AC_MSKB1)/* [15:15] */
#define SPM_CLK_CON_REG_SYSCLK0_SRC_MASK_B Fld(7, 16, AC_MSKB2)/* [22:16] */
#define SPM_CLK_CON_REG_SYSCLK1_SRC_MASK_B Fld(7, 23, AC_MSKW32)/* [29:23] */
#define SPM_PCM_PWR_IO_EN (SPM_BASE_ADDRESS + 0x002C)
#define PCM_PWR_IO_EN_RG_PCM_PWR_IO_EN Fld(8, 0, AC_FULLB0)/* [7:0] */
#define PCM_PWR_IO_EN_RG_RF_SYNC_EN Fld(8, 16, AC_FULLB2)/* [23:16] */

#define SPM_DRAMC_DPY_CLK_SW_CON_SEL (SPM_BASE_ADDRESS + 0x0460)
#define DRAMC_DPY_CLK_SW_CON_SEL_FULL Fld(32, 0, AC_FULLDW)/* [31:0] */
#define DRAMC_DPY_CLK_SW_CON_SEL_SW_DR_GATE_RETRY_EN_SEL Fld(2, 0, AC_MSKB0)/* [1:0] */
#define DRAMC_DPY_CLK_SW_CON_SEL_SW_EMI_CLK_OFF_SEL Fld(2, 2, AC_MSKB0)/* [3:2] */
#define DRAMC_DPY_CLK_SW_CON_SEL_SW_DPY_MODE_SW_SEL Fld(2, 4, AC_MSKB0)/* [5:4] */
#define DRAMC_DPY_CLK_SW_CON_SEL_SW_DMSUS_OFF_SEL Fld(2, 6, AC_MSKB0)/* [7:6] */
#define DRAMC_DPY_CLK_SW_CON_SEL_SW_MEM_CK_OFF_SEL Fld(2, 8, AC_MSKB1)/* [9:8] */
#define DRAMC_DPY_CLK_SW_CON_SEL_SW_DPY_2ND_DLL_EN_SEL Fld(2, 10, AC_MSKB1)/* [11:10] */
#define DRAMC_DPY_CLK_SW_CON_SEL_SW_DPY_DLL_EN_SEL Fld(2, 12, AC_MSKB1)/* [13:12] */
#define DRAMC_DPY_CLK_SW_CON_SEL_SW_DPY_DLL_CK_EN_SEL Fld(2, 14, AC_MSKB1)/* [15:14] */
#define DRAMC_DPY_CLK_SW_CON_SEL_SW_DPY_VREF_EN_SEL Fld(2, 16, AC_MSKB2)/* [17:16] */
#define DRAMC_DPY_CLK_SW_CON_SEL_SW_PHYPLL_EN_SEL Fld(2, 18, AC_MSKB2)/* [19:18] */
#define DRAMC_DPY_CLK_SW_CON_SEL_SW_DDRPHY_FB_CK_EN_SEL Fld(2, 20, AC_MSKB2)/* [21:20] */
#define DRAMC_DPY_CLK_SW_CON_SEL_SEPERATE_PHY_PWR_SEL Fld(1, 23, AC_MSKB2)/* [23:23] */
#define DRAMC_DPY_CLK_SW_CON_SEL_SW_SW_DMDRAMCSHU_ACK_SEL Fld(2, 24, AC_MSKB3)/* [25:24] */
#define DRAMC_DPY_CLK_SW_CON_SEL_SW_EMI_CLK_OFF_ACK_SEL Fld(2, 26, AC_MSKB3)/* [27:26] */
#define DRAMC_DPY_CLK_SW_CON_SEL_SW_DR_SHORT_QUEUE_ACK_SEL Fld(2, 28, AC_MSKB3)/* [29:28] */
#define DRAMC_DPY_CLK_SW_CON_SEL_SW_DRAMC_DFS_STA_SEL Fld(2, 30, AC_MSKB3)/* [31:30] */
#define SPM_DRAMC_DPY_CLK_SW_CON (SPM_BASE_ADDRESS + 0x0464)
#define DRAMC_DPY_CLK_SW_CON_SW_DR_GATE_RETRY_EN Fld(2, 0, AC_MSKB0)/* [1:0] */
#define DRAMC_DPY_CLK_SW_CON_SW_EMI_CLK_OFF Fld(2, 2, AC_MSKB0)/* [3:2] */
#define DRAMC_DPY_CLK_SW_CON_SW_DPY_MODE_SW Fld(2, 4, AC_MSKB0)/* [5:4] */
#define DRAMC_DPY_CLK_SW_CON_SW_DMSUS_OFF Fld(2, 6, AC_MSKB0)/* [7:6] */
#define DRAMC_DPY_CLK_SW_CON_SW_MEM_CK_OFF Fld(2, 8, AC_MSKB1)/* [9:8] */
#define DRAMC_DPY_CLK_SW_CON_SW_DPY_2ND_DLL_EN Fld(2, 10, AC_MSKB1)/* [11:10] */
#define DRAMC_DPY_CLK_SW_CON_SW_DPY_DLL_EN Fld(2, 12, AC_MSKB1)/* [13:12] */
#define DRAMC_DPY_CLK_SW_CON_SW_DPY_DLL_CK_EN Fld(2, 14, AC_MSKB1)/* [15:14] */
#define DRAMC_DPY_CLK_SW_CON_SW_DPY_VREF_EN Fld(2, 16, AC_MSKB2)/* [17:16] */
#define DRAMC_DPY_CLK_SW_CON_SW_PHYPLL_EN Fld(2, 18, AC_MSKB2)/* [19:18] */
#define DRAMC_DPY_CLK_SW_CON_SW_DDRPHY_FB_CK_EN Fld(2, 20, AC_MSKB2)/* [21:20] */
#define DRAMC_DPY_CLK_SW_CON_SC_DMDRAMCSHU_ACK Fld(2, 24, AC_MSKB3)/* [25:24] */
#define DRAMC_DPY_CLK_SW_CON_SC_EMI_CLK_OFF_ACK Fld(2, 26, AC_MSKB3)/* [27:26] */
#define DRAMC_DPY_CLK_SW_CON_SC_DR_SHORT_QUEUE_ACK Fld(2, 28, AC_MSKB3)/* [29:28] */
#define DRAMC_DPY_CLK_SW_CON_SC_DRAMC_DFS_STA Fld(2, 30, AC_MSKB3)/* [31:30] */
#define SPM_S1_MODE_CH (SPM_BASE_ADDRESS + 0x0468)
#define S1_MODE_CH_SPM_S1_MODE_CH Fld(2, 0, AC_MSKB0)/* [1:0] */
#define S1_MODE_CH_S1_EMI_CK_SWITCH Fld(2, 8, AC_MSKB1)/* [9:8] */
#define SPM_DRAMC_DPY_CLK_SW_CON_SEL2 (SPM_BASE_ADDRESS + 0x0470)
#define DRAMC_DPY_CLK_SW_CON_SEL2_FULL Fld(32, 0, AC_FULLDW)/* [31:0] */
#define DRAMC_DPY_CLK_SW_CON_SEL2_SW_PHYPLL_SHU_EN_SEL Fld(1, 0, AC_MSKB0)/* [0:0] */
#define DRAMC_DPY_CLK_SW_CON_SEL2_SW_PHYPLL2_SHU_EN_SEL Fld(1, 1, AC_MSKB0)/* [1:1] */
#define DRAMC_DPY_CLK_SW_CON_SEL2_SW_PHYPLL_MODE_SW_SEL Fld(1, 2, AC_MSKB0)/* [2:2] */
#define DRAMC_DPY_CLK_SW_CON_SEL2_SW_PHYPLL2_MODE_SW_SEL Fld(1, 3, AC_MSKB0)/* [3:3] */
#define DRAMC_DPY_CLK_SW_CON_SEL2_SW_DR_SHORT_QUEUE_SEL Fld(1, 4, AC_MSKB0)/* [4:4] */
#define DRAMC_DPY_CLK_SW_CON_SEL2_SW_DR_SHU_EN_SEL Fld(1, 5, AC_MSKB0)/* [5:5] */
#define DRAMC_DPY_CLK_SW_CON_SEL2_SW_DR_SHU_LEVEL_SEL Fld(1, 6, AC_MSKB0)/* [6:6] */
#define DRAMC_DPY_CLK_SW_CON_SEL2_SW_DPY_BCLK_ENABLE_SEL Fld(2, 8, AC_MSKB0)/* [9:8] */
#define DRAMC_DPY_CLK_SW_CON_SEL2_SW_SHU_RESTORE_SEL Fld(2, 10, AC_MSKB0)/* [11:10] */
#define DRAMC_DPY_CLK_SW_CON_SEL2_SW_DPHY_PRECAL_UP_SEL Fld(2, 12, AC_MSKB0)/* [13:12] */
#define DRAMC_DPY_CLK_SW_CON_SEL2_SW_DPHY_RXDLY_TRACK_EN_SEL Fld(2, 6, AC_MSKB0)/* [15:14] */
#define DRAMC_DPY_CLK_SW_CON_SEL2_SW_TX_TRACKING_DIS_SEL Fld(2, 16, AC_MSKB0)/* [17:16] */
#define SPM_DRAMC_DPY_CLK_SW_CON2 (SPM_BASE_ADDRESS + 0x0474)
#define DRAMC_DPY_CLK_SW_CON2_SW_PHYPLL_SHU_EN Fld(1, 0, AC_MSKB0)/* [0:0] */
#define DRAMC_DPY_CLK_SW_CON2_SW_PHYPLL2_SHU_EN Fld(1, 1, AC_MSKB0)/* [1:1] */
#define DRAMC_DPY_CLK_SW_CON2_SW_PHYPLL_MODE_SW Fld(1, 2, AC_MSKB0)/* [2:2] */
#define DRAMC_DPY_CLK_SW_CON2_SW_PHYPLL2_MODE_SW Fld(1, 3, AC_MSKB0)/* [3:3] */
#define DRAMC_DPY_CLK_SW_CON2_SW_DR_SHORT_QUEUE Fld(1, 4, AC_MSKB0)/* [4:4] */
#define DRAMC_DPY_CLK_SW_CON2_SW_DR_SHU_EN Fld(1, 5, AC_MSKB0)/* [5:5] */
#define DRAMC_DPY_CLK_SW_CON2_SW_DR_SHU_LEVEL Fld(2, 6, AC_MSKB0)/* [7:6] */
#define DRAMC_DPY_CLK_SW_CON2_SW_DPY_BCLK_ENABLE Fld(2, 8, AC_MSKB0)/* [9:8] */
#define DRAMC_DPY_CLK_SW_CON2_SW_SHU_RESTORE Fld(2, 10, AC_MSKB0)/* [11:10] */
#define DRAMC_DPY_CLK_SW_CON2_SW_DPHY_PRECAL_UP Fld(2, 12, AC_MSKB0)/* [13:12] */
#define DRAMC_DPY_CLK_SW_CON2_SW_DPHY_RXDLY_TRACK_EN Fld(2, 14, AC_MSKB0)/* [15:14] */
#define DRAMC_DPY_CLK_SW_CON2_SW_TX_TRACKING_DIS Fld(2, 16, AC_MSKB0)/* [17:16] */
#define SPM_DRAMC_DMYRD_CON (SPM_BASE_ADDRESS + 0x0478)
#define SPM_DRAMC_DMYRD_EN_MOD_SEL_CH1 Fld(1, 10, AC_MSKB1)/* [10:10] */
#define SPM_DRAMC_DMYRD_INTV_SEL_CH1 Fld(1, 9, AC_MSKB1)/* [9:9] */
#define SPM_DRAMC_DMYRD_EN_CH1 Fld(1, 8, AC_MSKB1)/* [8:8] */
#define SPM_DRAMC_DMYRD_EN_MOD_SEL_CH0 Fld(1, 2, AC_MSKB0)/* [2:2] */
#define SPM_DRAMC_DMYRD_INTV_SEL_CH0 Fld(1, 1, AC_MSKB0)/* [1:1] */
#define SPM_DRAMC_DMYRD_EN_CH0 Fld(1, 0, AC_MSKB0)/* [0:0] */
#endif
/*
 * #define SPM_SW_RSV_8 (SPM_BASE_ADDRESS + 0x0654)
 * #define SW_RSV_8_RX_TRACKING_EN Fld(2,6,AC_MSKB0)//[7:6]
 */

#if (fcFOR_CHIP_ID == fcA60868)
#include "A60868_Register_DDRPHY_MD32.h"
#include "A60868_Register_DDRPHY_NAO.h"
#include "A60868_Register_DDRPHY_AO.h"
#include "A60868_Register_DRAMC_AO.h"
#include "A60868_Register_DRAMC_NAO.h"
#include "Register_SYSTEM.h"
#elif (fcFOR_CHIP_ID == fcPetrus)
#include "Petrus_Register_DDRPHY_MD32.h"
#include "Petrus_Register_DDRPHY_NAO.h"
#include "Petrus_Register_DDRPHY_AO.h"
#include "Petrus_Register_DRAMC_AO.h"
#include "Petrus_Register_DRAMC_NAO.h"
#else
#include "Register_DDRPHY_MD32.h"
#include "Register_DDRPHY_NAO.h"
#include "Register_DDRPHY_AO.h"
#include "Register_DRAMC_AO.h"
#include "Register_DRAMC_NAO.h"
#include "Register_SYSTEM.h"
#endif

#if FOR_DV_SIMULATION_USED
#define Channel_A_DRAMC_NAO_BASE_VIRTUAL        0x40000
#define Channel_B_DRAMC_NAO_BASE_VIRTUAL        0x50000
#define Channel_A_DRAMC_AO_BASE_VIRTUAL	        0x60000
#define Channel_B_DRAMC_AO_BASE_VIRTUAL         0x70000
#define Channel_A_DDRPHY_NAO_BASE_VIRTUAL       0x80000
#define Channel_B_DDRPHY_NAO_BASE_VIRTUAL       0x90000
#define Channel_A_DDRPHY_AO_BASE_VIRTUAL        0xa0000
#define Channel_B_DDRPHY_AO_BASE_VIRTUAL        0xb0000
#define Channel_A_DDRPHY_DPM_BASE_VIRTUAL       0xc0000
#define MAX_BASE_VIRTUAL                        0xd0000
#else
// SW Virtual base address
#define Channel_A_DRAMC_NAO_BASE_VIRTUAL        0x40000
#define Channel_B_DRAMC_NAO_BASE_VIRTUAL        0x50000
#define Channel_C_DRAMC_NAO_BASE_VIRTUAL        0x60000
#define Channel_D_DRAMC_NAO_BASE_VIRTUAL        0x70000
#define Channel_A_DRAMC_AO_BASE_VIRTUAL	        0x80000
#define Channel_B_DRAMC_AO_BASE_VIRTUAL         0x90000
#define Channel_C_DRAMC_AO_BASE_VIRTUAL         0xA0000
#define Channel_D_DRAMC_AO_BASE_VIRTUAL         0xB0000
#define Channel_A_DDRPHY_NAO_BASE_VIRTUAL       0xC0000
#define Channel_B_DDRPHY_NAO_BASE_VIRTUAL       0xD0000
#define Channel_C_DDRPHY_NAO_BASE_VIRTUAL       0xE0000
#define Channel_D_DDRPHY_NAO_BASE_VIRTUAL       0xF0000
#define Channel_A_DDRPHY_AO_BASE_VIRTUAL        0x100000
#define Channel_B_DDRPHY_AO_BASE_VIRTUAL        0x110000
#define Channel_C_DDRPHY_AO_BASE_VIRTUAL        0x120000
#define Channel_D_DDRPHY_AO_BASE_VIRTUAL        0x130000
#define Channel_A_DDRPHY_DPM_BASE_VIRTUAL       0x140000
#define Channel_B_DDRPHY_DPM_BASE_VIRTUAL       0x150000
#define MAX_BASE_VIRTUAL                        0x160000
#endif

#define DRAMC_WBR 0x100010B4
#if (CHANNEL_NUM==4)
#define DRAMC_BROADCAST_ON 0x27f7f  //4CH
#else
#define DRAMC_BROADCAST_ON 0x7f  //2CH
#endif
#define DRAMC_BROADCAST_OFF 0x0

//Definitions indicating DRAMC, DDRPHY register shuffle offset
#define SHU_GRP_DRAMC_OFFSET      0x700
#define SHU_GRP_DDRPHY_OFFSET     0x700

#define DRAMC_REG_AO_SHU_OFFSET                 (0x700)
#define DRAMC_REG_AO_RANK_OFFSET                (0x200)
#define DRAMC_REG_AO_RANK0_WO_SHUFFLE_BASE_ADDR (DRAMC_REG_RK_TEST2_A1 - DRAMC_AO_BASE_ADDRESS) // 0x0500
#define DRAMC_REG_AO_RANK0_WO_SHUFFLE_END_ADDR  (DRAMC_REG_AO_RANK0_WO_SHUFFLE_BASE_ADDR + DRAMC_REG_AO_RANK_OFFSET)
#define DRAMC_REG_AO_RANK0_ROW_OFFSET_BASE_ADDR (DRAMC_REG_WO_MR_BACKUP_00_RK0_FSP0 - DRAMC_AO_BASE_ADDRESS) // 0x0900
#define DRAMC_REG_AO_RANK0_ROW_OFFSET_END_ADDR  (DRAMC_REG_AO_RANK0_ROW_OFFSET_BASE_ADDR + DRAMC_REG_AO_RANK_OFFSET)
#define DRAMC_REG_AO_RANK0_W_SHUFFLE0_BASE_ADDR (DRAMC_REG_SHURK_SELPH_DQ0 - DRAMC_AO_BASE_ADDRESS) // 0x1200
#define DRAMC_REG_AO_RANK0_W_SHUFFLE0_END_ADDR  (DRAMC_REG_AO_RANK0_W_SHUFFLE0_BASE_ADDR + DRAMC_REG_AO_RANK_OFFSET)
#define DRAMC_REG_AO_SHUFFLE0_BASE_ADDR         (DRAMC_REG_SHURK_SELPH_DQ0 - DRAMC_AO_BASE_ADDRESS) // 0x1200
#define DRAMC_REG_AO_SHUFFLE0_END_ADDR          (DRAMC_REG_SHU_ACTIM7 - DRAMC_AO_BASE_ADDRESS) // 0x16E8

#define DDRPHY_AO_B0_B1_OFFSET                  (0x180)
#define DDRPHY_AO_SHU_OFFSET                    (0x700)
#define DDRPHY_AO_RANK_OFFSET                   (0x80)
#define DDRPHY_AO_RANK0_B0_NON_SHU_BASE_ADDR    (DDRPHY_REG_RK_B0_RXDVS0 - DDRPHY_AO_BASE_ADDRESS) // 0x0060
#define DDRPHY_AO_RANK0_B0_NON_SHU_END_ADDR     (DDRPHY_AO_RANK0_B0_NON_SHU_BASE_ADDR + DDRPHY_AO_RANK_OFFSET)
#define DDRPHY_AO_RANK0_B1_NON_SHU_BASE_ADDR    (DDRPHY_REG_RK_B1_RXDVS0 - DDRPHY_AO_BASE_ADDRESS) // 0x01E0
#define DDRPHY_AO_RANK0_B1_NON_SHU_END_ADDR     (DDRPHY_AO_RANK0_B1_NON_SHU_BASE_ADDR + DDRPHY_AO_RANK_OFFSET)
#define DDRPHY_AO_RANK0_CA_NON_SHU_BASE_ADDR    (DDRPHY_REG_RK_CA_RXDVS0 - DDRPHY_AO_BASE_ADDRESS) // 0x0360
#define DDRPHY_AO_RANK0_CA_NON_SHU_END_ADDR     (DDRPHY_AO_RANK0_CA_NON_SHU_BASE_ADDR + DDRPHY_AO_RANK_OFFSET)
#define DDRPHY_AO_RANK0_B0_SHU0_BASE_ADDR       (DDRPHY_REG_SHU_R0_B0_TXDLY0 - DDRPHY_AO_BASE_ADDRESS) // 0x0760
#define DDRPHY_AO_RANK0_B0_SHU0_END_ADDR        (DDRPHY_AO_RANK0_B0_SHU0_BASE_ADDR + DDRPHY_AO_RANK_OFFSET)
#define DDRPHY_AO_RANK0_B1_SHU0_BASE_ADDR       (DDRPHY_REG_SHU_R0_B1_TXDLY0 - DDRPHY_AO_BASE_ADDRESS) // 0x08E0
#define DDRPHY_AO_RANK0_B1_SHU0_END_ADDR        (DDRPHY_AO_RANK0_B1_SHU0_BASE_ADDR + DDRPHY_AO_RANK_OFFSET)
#define DDRPHY_AO_RANK0_CA_SHU0_BASE_ADDR       (DDRPHY_REG_SHU_R0_CA_TXDLY0 - DDRPHY_AO_BASE_ADDRESS) // 0x0A60
#define DDRPHY_AO_RANK0_CA_SHU0_END_ADDR        (DDRPHY_AO_RANK0_CA_SHU0_BASE_ADDR + DDRPHY_AO_RANK_OFFSET)
#define DDRPHY_AO_RANK0_MISC_SHU0_BASE_ADDR     (DDRPHY_REG_MISC_SHU_RK_DQSCTL - DDRPHY_AO_BASE_ADDRESS) // 0x0BE0
#define DDRPHY_AO_RANK0_MISC_SHU0_END_ADDR      (DDRPHY_AO_RANK0_MISC_SHU0_BASE_ADDR + DDRPHY_AO_RANK_OFFSET)
#define DDRPHY_AO_SHUFFLE0_BASE_ADDR            (DDRPHY_REG_SHU_PHYPLL0 - DDRPHY_AO_BASE_ADDRESS) // 0x700
#define DDRPHY_AO_SHUFFLE0_END_ADDR             (DDRPHY_REG_MISC_SHU_CG_CTRL0 - DDRPHY_AO_BASE_ADDRESS) // 0xDA4

#define DDRPHY_NAO_DQSIEN_AUTOK_STATUS_RK_OFFSET        (0x20)
#define DDRPHY_NAO_GATING_STATUS_RK_OFFSET              (0x10)
#define DDRPHY_NAO_RANK0_B0_DQSIEN_AUTOK_STATUS_START   (DDRPHY_REG_DQSIEN_AUTOK_B0_RK0_STATUS0 - DDRPHY_NAO_BASE_ADDRESS) // 0x0600
#define DDRPHY_NAO_RANK0_B0_DQSIEN_AUTOK_STATUS_END     (DDRPHY_NAO_RANK0_B0_DQSIEN_AUTOK_STATUS_START + DDRPHY_NAO_DQSIEN_AUTOK_STATUS_RK_OFFSET)
#define DDRPHY_NAO_RANK0_B1_DQSIEN_AUTOK_STATUS_START   (DDRPHY_REG_DQSIEN_AUTOK_B1_RK0_STATUS0 - DDRPHY_NAO_BASE_ADDRESS) // 0x0640
#define DDRPHY_NAO_RANK0_B1_DQSIEN_AUTOK_STATUS_END     (DDRPHY_NAO_RANK0_B1_DQSIEN_AUTOK_STATUS_START + DDRPHY_NAO_DQSIEN_AUTOK_STATUS_RK_OFFSET)
#define DDRPHY_NAO_RANK0_CA_DQSIEN_AUTOK_STATUS_START   (DDRPHY_REG_DQSIEN_AUTOK_CA_RK0_STATUS0 - DDRPHY_NAO_BASE_ADDRESS) // 0x0680
#define DDRPHY_NAO_RANK0_CA_DQSIEN_AUTOK_STATUS_END     (DDRPHY_NAO_RANK0_CA_DQSIEN_AUTOK_STATUS_START + DDRPHY_NAO_DQSIEN_AUTOK_STATUS_RK_OFFSET)
#define DDRPHY_NAO_RANK0_GATING_STATUS_START            (DDRPHY_REG_GATING_ERR_LATCH_DLY_B0_RK0 - DDRPHY_NAO_BASE_ADDRESS) // 0x0420
#define DDRPHY_NAO_RANK0_GATING_STATUS_END              (DDRPHY_NAO_RANK0_GATING_STATUS_START + DDRPHY_NAO_GATING_STATUS_RK_OFFSET)

// HW Physical base address
#if defined(__DPM__)
/* MD32 address */
#undef Channel_A_DRAMC_AO_BASE_ADDRESS
#define Channel_A_DRAMC_AO_BASE_ADDRESS         0x300A2000
#undef Channel_B_DRAMC_AO_BASE_ADDRESS
#define Channel_B_DRAMC_AO_BASE_ADDRESS         0x300B2000
#undef Channel_C_DRAMC_AO_BASE_ADDRESS
#define Channel_C_DRAMC_AO_BASE_ADDRESS         0x0
#undef Channel_D_DRAMC_AO_BASE_ADDRESS
#define Channel_D_DRAMC_AO_BASE_ADDRESS         0x0
#undef Channel_A_DRAMC_NAO_BASE_ADDRESS
#define Channel_A_DRAMC_NAO_BASE_ADDRESS        0x300A8000
#undef Channel_B_DRAMC_NAO_BASE_ADDRESS
#define Channel_B_DRAMC_NAO_BASE_ADDRESS        0x300B8000
#undef Channel_C_DRAMC_NAO_BASE_ADDRESS
#define Channel_C_DRAMC_NAO_BASE_ADDRESS        0x0
#undef Channel_D_DRAMC_NAO_BASE_ADDRESS
#define Channel_D_DRAMC_NAO_BASE_ADDRESS        0x0
#undef Channel_A_DDRPHY_AO_BASE_ADDRESS
#define Channel_A_DDRPHY_AO_BASE_ADDRESS        0x300A6000
#undef Channel_B_DDRPHY_AO_BASE_ADDRESS
#define Channel_B_DDRPHY_AO_BASE_ADDRESS        0x300B6000
#undef Channel_C_DDRPHY_AO_BASE_ADDRESS
#define Channel_C_DDRPHY_AO_BASE_ADDRESS        0x0
#undef Channel_D_DDRPHY_AO_BASE_ADDRESS
#define Channel_D_DDRPHY_AO_BASE_ADDRESS        0x0
#undef Channel_A_DDRPHY_NAO_BASE_ADDRESS
#define Channel_A_DDRPHY_NAO_BASE_ADDRESS       0x300AA000
#undef Channel_B_DDRPHY_NAO_BASE_ADDRESS
#define Channel_B_DDRPHY_NAO_BASE_ADDRESS       0x300BA000
#undef Channel_C_DDRPHY_NAO_BASE_ADDRESS
#define Channel_C_DDRPHY_NAO_BASE_ADDRESS       0x0
#undef Channel_D_DDRPHY_NAO_BASE_ADDRESS
#define Channel_D_DDRPHY_NAO_BASE_ADDRESS       0x0
#undef Channel_A_DDRPHY_DPM_BASE_ADDRESS
#define Channel_A_DDRPHY_DPM_BASE_ADDRESS       0x30040000
#elif (FOR_DV_SIMULATION_USED)
#undef Channel_A_DRAMC_AO_BASE_ADDRESS
#define Channel_A_DRAMC_AO_BASE_ADDRESS         0x10000
#undef Channel_B_DRAMC_AO_BASE_ADDRESS
#define Channel_B_DRAMC_AO_BASE_ADDRESS         0x40000
#undef Channel_C_DRAMC_AO_BASE_ADDRESS
#define Channel_C_DRAMC_AO_BASE_ADDRESS         0x0
#undef Channel_D_DRAMC_AO_BASE_ADDRESS
#define Channel_D_DRAMC_AO_BASE_ADDRESS         0x0

#undef Channel_A_DRAMC_NAO_BASE_ADDRESS
#define Channel_A_DRAMC_NAO_BASE_ADDRESS        0x20000
#undef Channel_B_DRAMC_NAO_BASE_ADDRESS
#define Channel_B_DRAMC_NAO_BASE_ADDRESS        0x50000
#undef Channel_C_DRAMC_NAO_BASE_ADDRESS
#define Channel_C_DRAMC_NAO_BASE_ADDRESS         0x0
#undef Channel_D_DRAMC_NAO_BASE_ADDRESS
#define Channel_D_DRAMC_NAO_BASE_ADDRESS         0x0

#undef Channel_A_DDRPHY_AO_BASE_ADDRESS
#define Channel_A_DDRPHY_AO_BASE_ADDRESS        0x30000
#undef Channel_B_DDRPHY_AO_BASE_ADDRESS
#define Channel_B_DDRPHY_AO_BASE_ADDRESS        0x60000
#undef Channel_C_DDRPHY_AO_BASE_ADDRESS
#define Channel_C_DDRPHY_AO_BASE_ADDRESS        0x0
#undef Channel_D_DDRPHY_AO_BASE_ADDRESS
#define Channel_D_DDRPHY_AO_BASE_ADDRESS        0x0

#undef Channel_A_DDRPHY_NAO_BASE_ADDRESS
#define Channel_A_DDRPHY_NAO_BASE_ADDRESS       0x70000
#undef Channel_B_DDRPHY_NAO_BASE_ADDRESS
#define Channel_B_DDRPHY_NAO_BASE_ADDRESS       0x80000
#undef Channel_C_DDRPHY_NAO_BASE_ADDRESS
#define Channel_C_DDRPHY_NAO_BASE_ADDRESS        0x0
#undef Channel_D_DDRPHY_NAO_BASE_ADDRESS
#define Channel_D_DDRPHY_NAO_BASE_ADDRESS        0x0

#undef Channel_A_DDRPHY_DPM_BASE_ADDRESS
#define Channel_A_DDRPHY_DPM_BASE_ADDRESS       0x90000
#elif(HAPS_FPFG_A60868 ==0)
#undef Channel_A_DRAMC_AO_BASE_ADDRESS
#define Channel_A_DRAMC_AO_BASE_ADDRESS         0x10230000
#undef Channel_B_DRAMC_AO_BASE_ADDRESS
#define Channel_B_DRAMC_AO_BASE_ADDRESS         0x10240000
#undef Channel_C_DRAMC_AO_BASE_ADDRESS
#define Channel_C_DRAMC_AO_BASE_ADDRESS         0x10250000
#undef Channel_D_DRAMC_AO_BASE_ADDRESS
#define Channel_D_DRAMC_AO_BASE_ADDRESS         0x10260000
#undef Channel_A_DRAMC_NAO_BASE_ADDRESS
#define Channel_A_DRAMC_NAO_BASE_ADDRESS        0x10234000
#undef Channel_B_DRAMC_NAO_BASE_ADDRESS
#define Channel_B_DRAMC_NAO_BASE_ADDRESS        0x10244000
#undef Channel_C_DRAMC_NAO_BASE_ADDRESS
#define Channel_C_DRAMC_NAO_BASE_ADDRESS        0x10254000
#undef Channel_D_DRAMC_NAO_BASE_ADDRESS
#define Channel_D_DRAMC_NAO_BASE_ADDRESS        0x10264000
#undef Channel_A_DDRPHY_AO_BASE_ADDRESS
#define Channel_A_DDRPHY_AO_BASE_ADDRESS        0x10238000
#undef Channel_B_DDRPHY_AO_BASE_ADDRESS
#define Channel_B_DDRPHY_AO_BASE_ADDRESS        0x10248000
#undef Channel_C_DDRPHY_AO_BASE_ADDRESS
#define Channel_C_DDRPHY_AO_BASE_ADDRESS        0x10258000
#undef Channel_D_DDRPHY_AO_BASE_ADDRESS
#define Channel_D_DDRPHY_AO_BASE_ADDRESS        0x10268000
#undef Channel_A_DDRPHY_NAO_BASE_ADDRESS
#define Channel_A_DDRPHY_NAO_BASE_ADDRESS       0x10236000
#undef Channel_B_DDRPHY_NAO_BASE_ADDRESS
#define Channel_B_DDRPHY_NAO_BASE_ADDRESS       0x10246000
#undef Channel_C_DDRPHY_NAO_BASE_ADDRESS
#define Channel_C_DDRPHY_NAO_BASE_ADDRESS       0x10256000
#undef Channel_D_DDRPHY_NAO_BASE_ADDRESS
#define Channel_D_DDRPHY_NAO_BASE_ADDRESS       0x10266000
#undef Channel_A_DDRPHY_DPM_BASE_ADDRESS
#define Channel_A_DDRPHY_DPM_BASE_ADDRESS       0x10940000
#undef Channel_B_DDRPHY_DPM_BASE_ADDRESS
#define Channel_B_DDRPHY_DPM_BASE_ADDRESS       0x10A40000
#else  // A60868 FPGA Base Address
#undef Channel_A_DRAMC_AO_BASE_ADDRESS
#define Channel_A_DRAMC_AO_BASE_ADDRESS         0x40000
#undef Channel_B_DRAMC_AO_BASE_ADDRESS
#define Channel_B_DRAMC_AO_BASE_ADDRESS         0x0
#undef Channel_C_DRAMC_AO_BASE_ADDRESS
#define Channel_C_DRAMC_AO_BASE_ADDRESS         0x0
#undef Channel_D_DRAMC_AO_BASE_ADDRESS
#define Channel_D_DRAMC_AO_BASE_ADDRESS         0x0
#undef Channel_A_DRAMC_NAO_BASE_ADDRESS
#define Channel_A_DRAMC_NAO_BASE_ADDRESS        0x10000
#undef Channel_B_DRAMC_NAO_BASE_ADDRESS
#define Channel_B_DRAMC_NAO_BASE_ADDRESS        0x0
#undef Channel_C_DRAMC_NAO_BASE_ADDRESS
#define Channel_C_DRAMC_NAO_BASE_ADDRESS        0x0
#undef Channel_D_DRAMC_NAO_BASE_ADDRESS
#define Channel_D_DRAMC_NAO_BASE_ADDRESS        0x0
#undef Channel_A_DDRPHY_AO_BASE_ADDRESS
#define Channel_A_DDRPHY_AO_BASE_ADDRESS        0x70000
#undef Channel_B_DDRPHY_AO_BASE_ADDRESS
#define Channel_B_DDRPHY_AO_BASE_ADDRESS        0x0
#undef Channel_C_DDRPHY_AO_BASE_ADDRESS
#define Channel_C_DDRPHY_AO_BASE_ADDRESS        0x0
#undef Channel_D_DDRPHY_AO_BASE_ADDRESS
#define Channel_D_DDRPHY_AO_BASE_ADDRESS        0x0
#undef Channel_A_DDRPHY_NAO_BASE_ADDRESS
#define Channel_A_DDRPHY_NAO_BASE_ADDRESS       0x80000
#undef Channel_B_DDRPHY_NAO_BASE_ADDRESS
#define Channel_B_DDRPHY_NAO_BASE_ADDRESS       0x0
#undef Channel_C_DDRPHY_NAO_BASE_ADDRESS
#define Channel_C_DDRPHY_NAO_BASE_ADDRESS       0x0
#undef Channel_D_DDRPHY_NAO_BASE_ADDRESS
#define Channel_D_DDRPHY_NAO_BASE_ADDRESS       0x0
#undef Channel_A_DDRPHY_DPM_BASE_ADDRESS
#define Channel_A_DDRPHY_DPM_BASE_ADDRESS       0x100000
#undef Channel_B_DDRPHY_DPM_BASE_ADDRESS
#define Channel_B_DDRPHY_DPM_BASE_ADDRESS       0x0
#endif

#define CHK_INCLUDE_LOCAL_HEADER "\n ==> Include local header but not one at DV SERVER\n\n"


#endif // _A60868_REGISTER_H_
