C_OPTION += -DDA_MODE_FPGA=0
C_OPTION += -DDA_ENABLE_SECURITY=1
C_OPTION += -DDA_VER_CHECK_EN=1
C_OPTION += -DDA_ENABLE_MULTI_THREAD=1

C_OPTION += -DDA_ENABLE_SRAM_FLASH=0

ifeq ($(DA_BUILD_STAGE),1)
    C_OPTION += -DMMC_POLLING_MODE=1
    C_OPTION += -DUFS_POLLING_MODE=1
else
    C_OPTION += -DMMC_POLLING_MODE=1
    C_OPTION += -DUFS_POLLING_MODE=0
    C_OPTION += -DDA_ENABLE_DCACHE=1
endif
