C_OPTION += -DDA_MODE_FPGA=1
C_OPTION += -DDA_ENABLE_SECURITY=0
C_OPTION += -DDA_ENABLE_MULTI_THREAD=0
C_OPTION += -DDA_ENABLE_SRAM_FLASH=0

ifeq ($(DA_BUILD_STAGE),1)
    C_OPTION += -DMMC_POLLING_MODE=1
    C_OPTION += -DUFS_POLLING_MODE=1
else
    C_OPTION += -DMMC_POLLING_MODE=1
    C_OPTION += -DUFS_POLLING_MODE=1
endif
