###################################################################
# flag
###################################################################

MOD_SRC  = 
MOD_OBJ  = $(OBJ_PATH)

###################################################################
# source files
# - add your file here !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
###################################################################

SUBDIRS += efuse
SUBDIRS += emi
SUBDIRS += irq
SUBDIRS += mmc
SUBDIRS += pll
SUBDIRS += pmic
SUBDIRS += power
SUBDIRS += rtc_bbpu
SUBDIRS += uart
SUBDIRS += ufs
SUBDIRS += usb
SUBDIRS += wdt
SUBDIRS += timer
SUBDIRS += random
SUBDIRS += gpio
SUBDIRS += pcie
SUBDIRS += cldma
SUBDIRS += nand
SUBDIRS += i2c

###################################################################
# target
###################################################################

include $(COMMON_FILE_MK)

###################################################################
# include sub dir
###################################################################

include $(COMMON_DIR_MK)
