DA_USE_PL_HW_DRV := yes
DA_OUT ?= $(TARGET_OUT_INTERMEDIATES)
$(DA_MODE)_OUT := $(DA_OUT)/$(DA_MODE)_OBJ
$(DA_MODE)_ROOT_OUT := $(abspath $($(DA_MODE)_OUT))
BUILT_$(DA_MODE)_TARGET := $($(DA_MODE)_OUT)/bin/$(DA_MODE).bin
PREBUILT_$(DA_MODE)_TARGET := $(DA_DIR)/platform/$(TARGET_BOARD_PLATFORM)/flash/make_script/$(DA_MODE).bin
INSTALLED_$(DA_MODE)_TARGET := $(PRODUCT_OUT)/download_agent/$(DA_MODE).bin
BUILT_$(DA_MODE)_FLASH_XML := $($(DA_MODE)_OUT)/bin/flash.xml
INSTALLED_$(DA_MODE)_FLASH_XML := $(PRODUCT_OUT)/download_agent/flash.xml
BUILT_$(DA_MODE)_FLASH_XSD := $($(DA_MODE)_OUT)/bin/flash.xsd
INSTALLED_$(DA_MODE)_FLASH_XSD := $(PRODUCT_OUT)/download_agent/flash.xsd
$(DA_MODE)_MAKE_OPTION := $(if $(SHOW_COMMANDS),,-s) -f Makefile.DA DA_OUT=$($(DA_MODE)_ROOT_OUT) MTK_PROJECT=$(my_da_project) DA_MODE=$(DA_MODE) DA_USE_PL_HW_DRV=$(DA_USE_PL_HW_DRV)
ifdef PERL
  $(DA_MODE)_MAKE_OPTION += PERL=$(abspath $(PERL))
endif
$(BUILT_$(DA_MODE)_TARGET): PRIVATE_PREBUILT_BIN := $(PREBUILT_$(DA_MODE)_TARGET)
$(BUILT_$(DA_MODE)_TARGET): PRIVATE_DA_MAKE_OPTION := $($(DA_MODE)_MAKE_OPTION)
$(BUILT_$(DA_MODE)_TARGET): $(DA_MAKE_DEPENDENCIES)
	$(hide) mkdir -p $(dir $@)
	$(PREBUILT_MAKE_PREFIX)$(MAKE) -C $(DA_DIR) $(PRIVATE_DA_MAKE_OPTION)
ifneq (,$(wildcard $(PREBUILT_$(DA_MODE)_TARGET)))
	$(hide) cp -f $(PRIVATE_PREBUILT_BIN) $@
endif
$(BUILT_$(DA_MODE)_FLASH_XML) $(BUILT_$(DA_MODE)_FLASH_XSD): $(BUILT_$(DA_MODE)_TARGET)
$(INSTALLED_$(DA_MODE)_TARGET): $(BUILT_$(DA_MODE)_TARGET) | $(ACP)
	$(copy-file-to-target)
$(INSTALLED_$(DA_MODE)_FLASH_XML): $(BUILT_$(DA_MODE)_FLASH_XML) $(BUILT_$(DA_MODE)_TARGET) | $(ACP)
	$(copy-file-to-target)
$(INSTALLED_$(DA_MODE)_FLASH_XSD): $(BUILT_$(DA_MODE)_FLASH_XSD) $(BUILT_$(DA_MODE)_TARGET) | $(ACP)
	$(copy-file-to-target)
.PHONY: DA
droidcore DA: $(INSTALLED_$(DA_MODE)_TARGET) $(INSTALLED_$(DA_MODE)_FLASH_XML) $(INSTALLED_$(DA_MODE)_FLASH_XSD)
