ifneq (,$(PL_MODE))
  PRELOADER_OUT := $(TARGET_OUT_INTERMEDIATES)/PRELOADER_$(PL_MODE)_OBJ
  INSTALLED_PRELOADER_TARGET := $(PRODUCT_OUT)/preloader_$(PRELOADER_TARGET_PRODUCT)_$(PL_MODE).bin
  BUILT_PRELOADER_TARGET := $(PRELOADER_OUT)/bin/preloader_$(PRELOADER_TARGET_PRODUCT)_$(PL_MODE).bin
  PRELOADER_BIN := $(PRODUCT_OUT)/preloader_$(PL_MODE).bin
  TARGET_PRELOADER := $(PRODUCT_OUT)/preloader_$(PL_MODE).img
  MTK_OTA_PREPROCESS_EXTRA_IMAGES := $(MTK_OTA_PREPROCESS_EXTRA_IMAGES) $(notdir $(TARGET_PRELOADER))
  BOARD_PACK_RADIOIMAGES := $(BOARD_PACK_RADIOIMAGES) $(notdir $(TARGET_PRELOADER))
  INSTALLED_RADIOIMAGE_TARGET := $(INSTALLED_RADIOIMAGE_TARGET) $(TARGET_PRELOADER)
  ifeq ($(CFG_PRELOADER_EXTENSION), 1)
    BUILT_LOADER_EXT_TARGET := $(PRELOADER_OUT)/bin/loader_ext.img
    INSTALLED_LOADER_EXT_TARGET := $(PRODUCT_OUT)/loader_ext_$(PL_MODE).img
  endif
else
  PRELOADER_OUT := $(TARGET_OUT_INTERMEDIATES)/PRELOADER_OBJ
  INSTALLED_PRELOADER_TARGET := $(PRODUCT_OUT)/preloader_$(PRELOADER_TARGET_PRODUCT).bin
  BUILT_PRELOADER_TARGET := $(PRELOADER_OUT)/bin/preloader_$(PRELOADER_TARGET_PRODUCT).bin
  PRELOADER_BIN := $(PRODUCT_OUT)/preloader.bin
  TARGET_PRELOADER := $(PRODUCT_OUT)/preloader.img
  MTK_OTA_PREPROCESS_EXTRA_IMAGES := $(MTK_OTA_PREPROCESS_EXTRA_IMAGES) $(notdir $(TARGET_PRELOADER))
  BOARD_PACK_RADIOIMAGES := $(BOARD_PACK_RADIOIMAGES) $(notdir $(TARGET_PRELOADER))
  INSTALLED_RADIOIMAGE_TARGET := $(INSTALLED_RADIOIMAGE_TARGET) $(TARGET_PRELOADER) $(INSTALLED_PRELOADER_TARGET)
  ifeq ($(CFG_PRELOADER_EXTENSION), 1)
    BUILT_LOADER_EXT_TARGET := $(PRELOADER_OUT)/bin/loader_ext.img
    INSTALLED_LOADER_EXT_TARGET := $(PRODUCT_OUT)/loader_ext.img
    LOADER_EXT_IMAGE_NAME := $(notdir $(INSTALLED_LOADER_EXT_TARGET))
  endif
  INSTALLED_EFUSE_IMAGE_TARGET := $(PRODUCT_OUT)/efuse.img
endif

  PRELOADER_ROOT_OUT := $(if $(filter /% ~%,$(PRELOADER_OUT)),,$(PRELOADER_ROOT_DIR)/)$(PRELOADER_OUT)
  PRELOADER_MAKE_OPTION := $(if $(SHOW_COMMANDS),,-s) -f Makefile PRELOADER_ROOT_DIR=$(PRELOADER_ROOT_DIR) PRELOADER_OUT=$(PRELOADER_ROOT_OUT) MTK_PROJECT=$(PRELOADER_TARGET_PRODUCT) TOOL_PATH=$(PRELOADER_ROOT_DIR)/device/mediatek/build/build/tools ROOTDIR=$(PRELOADER_ROOT_DIR) PL_MODE=$(PL_MODE)
ifdef PERL
  PRELOADER_MAKE_OPTION += PERL=$(abspath $(PERL))
endif

ifeq ($(wildcard $(TARGET_PREBUILT_PRELOADER)),)
PRELOADER_MAKE_DEPENDENCIES := $(shell find $(PRELOADER_DIR) -name .git -prune -o -type f | sort)
PRELOADER_MAKE_DEPENDENCIES := $(filter-out %/.git %/.gitignore %/.gitattributes,$(PRELOADER_MAKE_DEPENDENCIES))

.KATI_RESTAT: $(BUILT_PRELOADER_TARGET)
$(BUILT_PRELOADER_TARGET): PRIVATE_PRELOADER_MAKE_OPTION := $(PRELOADER_MAKE_OPTION)
$(BUILT_PRELOADER_TARGET): $(PRELOADER_MAKE_DEPENDENCIES)
	$(hide) mkdir -p $(dir $@)
	$(PREBUILT_MAKE_PREFIX)$(MAKE) -C $(PRELOADER_DIR) $(PRIVATE_PRELOADER_MAKE_OPTION)

endif#TARGET_PREBUILT_PRELOADER

ifneq ($(INSTALLED_PRELOADER_TARGET),$(BUILT_PRELOADER_TARGET))
$(INSTALLED_PRELOADER_TARGET): $(BUILT_PRELOADER_TARGET) | $(ACP)
	$(copy-file-to-target)
endif

$(PRELOADER_BIN): $(INSTALLED_PRELOADER_TARGET)
	$(hide) mkdir -p $(dir $@)
	$(hide) cp -f $< $@

ifeq ($(wildcard $(PRELOADER_HEADER_BLOCK)),)
$(TARGET_PRELOADER): $(INSTALLED_PRELOADER_TARGET) $(PRELOADER_DIR)/tools/gen-preloader-img.py
	$(hide) $(PRELOADER_DIR)/tools/gen-preloader-img.py $< $@
else
$(TARGET_PRELOADER): $(PRELOADER_HEADER_BLOCK) $(INSTALLED_PRELOADER_TARGET)
	$(hide) cat $^ > $@
endif

ifeq (,$(PL_MODE))
ifneq ($(wildcard $(PRELOADER_HEADER_BLOCK)),)
preloader pl: $(PRODUCT_OUT)/preloader_ufs.img
$(PRODUCT_OUT)/preloader_ufs.img: $(PRELOADER_HEADER_BLOCK) $(INSTALLED_PRELOADER_TARGET)
	$(hide) mkdir -p $(dir $@)
	$(hide) cat $^ > $@

preloader pl: $(PRODUCT_OUT)/preloader_emmc.img
$(PRODUCT_OUT)/preloader_emmc.img: $(PRELOADER_HEADER_BLOCK) $(INSTALLED_PRELOADER_TARGET)
	$(hide) mkdir -p $(dir $@)
	$(hide) cat $^ > $@
endif
preloader pl: $(PRODUCT_OUT)/preloader_raw.img
$(PRODUCT_OUT)/preloader_raw.img: $(INSTALLED_PRELOADER_TARGET)
	$(hide) mkdir -p $(dir $@)
	$(hide) cp $< $@
endif

preloader pl: $(INSTALLED_PRELOADER_TARGET) $(TARGET_PRELOADER) $(PRELOADER_BIN)
ifeq ($(CFG_PRELOADER_EXTENSION), 1)
.PHONY: $(LOADER_EXT_IMAGE_NAME)
preloader pl: $(INSTALLED_LOADER_EXT_TARGET) $(LOADER_EXT_IMAGE_NAME)
$(LOADER_EXT_IMAGE_NAME):
$(INSTALLED_LOADER_EXT_TARGET): PRIVATE_BUILT_LOADER_EXT_TARGET := $(BUILT_LOADER_EXT_TARGET)
$(INSTALLED_LOADER_EXT_TARGET): $(BUILT_PRELOADER_TARGET)
	$(hide) cp -f $(PRIVATE_BUILT_LOADER_EXT_TARGET) $@
endif

ifeq (,$(PL_MODE))
ifeq (yes,$(PRELOADER_EFUSE_WRITER_SUPPORT))
preloader pl: $(INSTALLED_EFUSE_IMAGE_TARGET)
$(INSTALLED_EFUSE_IMAGE_TARGET): PRIVATE_EFUSE_IMAGE_TARGET := $(PRELOADER_OUT)/bin/efuse.img
$(INSTALLED_EFUSE_IMAGE_TARGET): $(BUILT_PRELOADER_TARGET)
	$(hide) cp -f $(PRIVATE_EFUSE_IMAGE_TARGET) $@
endif
endif

ifneq (,$(PL_MODE))
.PHONY: clean-preloader-$(PL_MODE)
clean-preloader: clean-preloader-$(PL_MODE)
clean-preloader-$(PL_MODE): PRIVATE_INSTALLED_PRELOADER_TARGET := $(INSTALLED_PRELOADER_TARGET)
clean-preloader-$(PL_MODE): PRIVATE_TARGET_PRELOADER := $(TARGET_PRELOADER)
clean-preloader-$(PL_MODE): PRIVATE_PRELOADER_OUT := $(PRELOADER_OUT)
clean-preloader-$(PL_MODE):
	$(hide) rm -rf $(PRIVATE_INSTALLED_PRELOADER_TARGET) $(PRIVATE_TARGET_PRELOADER) $(PRIVATE_PRELOADER_OUT) $(INSTALLED_LOADER_EXT_TARGET)
else
.PHONY: clean-preloader-normal
clean-preloader: clean-preloader-normal
clean-preloader-normal: PRIVATE_INSTALLED_PRELOADER_TARGET := $(INSTALLED_PRELOADER_TARGET)
clean-preloader-normal: PRIVATE_TARGET_PRELOADER := $(TARGET_PRELOADER)
clean-preloader-normal: PRIVATE_PRELOADER_OUT := $(PRELOADER_OUT)
clean-preloader-normal:
	$(hide) rm -rf $(PRIVATE_INSTALLED_PRELOADER_TARGET) $(PRIVATE_TARGET_PRELOADER) $(PRIVATE_PRELOADER_OUT) $(INSTALLED_LOADER_EXT_TARGET)
endif
