#pragma once

#include "cldma_interface.h"
#include "clock_interface.h"
#include "efuse_interface.h"
#include "emi_interface.h"
#include "gpio_interface.h"
#include "gpt_timer_interface.h"
#include "irq_interface.h"
#include "mmc_interface.h"
#include "nand_interface.h"
#include "nor_interface.h"
#include "pcie_interface.h"
#include "pmic_interface.h"
#include "power_interface.h"
#include "rid_interface.h"
#include "timer_interface.h"
#include "uart_interface.h"
#include "ufs_interface.h"
#include "usb_interface.h"
#include "wdt_interface.h"

